<a href="https://colab.research.google.com/github/Gabizinha88/CidadesDataframe/blob/main/CidadesDataframe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


** **negrito**1- Apresente em tela (output) toda a base de dados. Pontuação: 0,5 pontos**



```
# Isto está formatado como código
```

# ** **negrito**1- Apresente em tela (output) toda a base de dados. Pontuação: 0,5 pontos**

In [31]:
import pandas as pd

# começando meu dataframe baseado em cidades de amigos
data = {
    'Nome': ['Clebler', 'Michael', 'Maria Lua', 'Junior Largatixa', 'Tarik Jr', 'Yasmin'],
    'Idade': [23, 34, 10, 36, 13, 27],
    'Cidade': ['Jardim de Piranhas', 'Xique Xique', 'Fercal', 'New York', 'Rio de Janeiro', 'London'],
    'Estado': ['RN', 'BA', 'DF', 'NY', 'RJ', 'ENG'],
    'CEP': ['59324-000', '44900-000', '73255-000', '10001', '20000-000', 'WC2N 5DU'],
    'País': ['Brasil', 'Brasil', 'Brasil', 'Estados Unidos', 'Brasil', 'Reino Unido']
}

# importando os dados
cidades = pd.DataFrame(data)

# 1. apresentar a saida completa
print("Base de dados completa:")
print(cidades)

Base de dados completa:
               Nome  Idade              Cidade Estado        CEP  \
0           Clebler     23  Jardim de Piranhas     RN  59324-000
1           Michael     34         Xique Xique     BA  44900-000
2         Maria Lua     10              Fercal     DF  73255-000
3  Junior Largatixa     36            New York     NY      10001
4          Tarik Jr     13      Rio de Janeiro     RJ  20000-000
5            Yasmin     27              London    ENG   WC2N 5DU

             País
0          Brasil
1          Brasil
2          Brasil
3  Estados Unidos
4          Brasil
5     Reino Unido

# *2- Apresente o tamanho do seu dataframe (quantas colunas x linhas).*

In [8]:
num_linhas, num_colunas = cidades.shape
print(f"O DataFrame tem {num_linhas} linhas e {num_colunas} colunas.")

O DataFrame tem 6 linhas e 6 colunas.

#3- **negrito** Acesse a linha (x) e apresente em tela todas as características do item.

In [9]:
cidades = pd.DataFrame(data)

# Vamos definir a linha que queremos acessar e seu indice
x = 2

# Olhando se o indice se encontra no mesmo intervalo
if 0 <= x < len(cidades):
    # Acessando a linha x e exibindo todas as características
    print(f"Características do item na linha {x}:")
    print(cidades.iloc[x])
else:
    print(f"O índice {x} está fora do intervalo do DataFrame.")

Características do item na linha 2:
Nome      Maria Lua
Idade            10
Cidade       Fercal
Estado           DF
CEP       73255-000
País         Brasil
Name: 2, dtype: object

**4- Verifique se o dataframe está vazio. Pontuação: 0,5 pontos**

In [11]:
is_empty = cidades.empty

# 2. Verificar se o DataFrame está vazio ou não
if is_empty:
    print("\nO DataFrame está vazio.")
else:
    print("\nO DataFrame não está vazio.")

O DataFrame não está vazio.

**5- Apresente em tela os 5 primeiros registros da base de dados. Pontuação: 0,5 pontos**

In [ ]:
print("Os 5 primeiros registros da base de dados:")
print(cidades.head())

**6- Exclua um item (linha) de sua base de dados. Pontuação: 0,5 pontos**

In [28]:
# Excluir a última linha
cidades = cidades.drop(5)
cidades

,Nome,Idade,Cidade,Estado,CEP,País
0,Clebler,23,Jardim de Piranhas,RN,59324-000,Brasil
1,Michael,34,Xique Xique,BA,44900-000,Brasil
2,Maria Lua,10,Fercal,DF,73255-000,Brasil
3,Junior Largatixa,36,New York,NY,10001,Estados Unidos
4,Tarik Jr,13,Rio de Janeiro,RJ,20000-000,Brasil

**7- Adicione um item (linha) na sua base de dados. Pontuação: 0,5 pontos**

In [32]:
# Adicionar uma nova linha
new_row = {
    'Nome': 'Alice',
    'Idade': 29,
    'Cidade': 'Paris',
    'Estado': 'Île-de-France',
    'CEP': '75000',
    'País': 'França'
}

cidades.loc[len(cidades)] = new_row

print("\nBase de dados após adicionar uma nova linha:")
print(cidades)

Base de dados após adicionar uma nova linha:
               Nome  Idade              Cidade         Estado        CEP  \
0           Clebler     23  Jardim de Piranhas             RN  59324-000
1           Michael     34         Xique Xique             BA  44900-000
2         Maria Lua     10              Fercal             DF  73255-000
3  Junior Largatixa     36            New York             NY      10001
4          Tarik Jr     13      Rio de Janeiro             RJ  20000-000
5            Yasmin     27              London            ENG   WC2N 5DU
6             Alice     29               Paris  Île-de-France      75000

             País
0          Brasil
1          Brasil
2          Brasil
3  Estados Unidos
4          Brasil
5     Reino Unido
6          França

8- **Transponha a coluna para a linha em sua base de dados. Pontuação: 0,5 pontos**

In [37]:
cidades_transposed = cidades.T

# Apresentar o DataFrame transposto
print("\nBase de dados transposta:")
print(cidades_transposed)

Base de dados transposta:
                         0            1          2                 3  \
Nome               Clebler      Michael  Maria Lua  Junior Largatixa
Idade                   23           34         10                36
Cidade  Jardim de Piranhas  Xique Xique     Fercal          New York
Estado                  RN           BA         DF                NY
CEP              59324-000    44900-000  73255-000             10001
País                Brasil       Brasil     Brasil    Estados Unidos

                     4            5              6
Nome          Tarik Jr       Yasmin          Alice
Idade               13           27             29
Cidade  Rio de Janeiro       London          Paris
Estado              RJ          ENG  Île-de-France
CEP          20000-000     WC2N 5DU          75000
País            Brasil  Reino Unido         França

**9- Apresente em tela somente a 1ª e a 2ª coluna (rótulo) da base de dados. Pontuação: 0,5**

In [38]:
cidades[["Nome", "Idade"]]

               Nome  Idade
0           Clebler     23
1           Michael     34
2         Maria Lua     10
3  Junior Largatixa     36
4          Tarik Jr     13
5            Yasmin     27
6             Alice     29